apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: keras-ready-env
  name: keras-ready-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keras-ready-env
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: keras-ready-env
    spec:
      containers:
      - image: yanuragaj/dietpred:v4
        name: dietpred
        resources: {}
status: {}
