apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: keras-ready-env
    app.kubernetes.io/managed-by: Helm
  name: keras-ready-env
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: keras-ready-env
  type: NodePort
status:
  loadBalancer: {}
